### ISSUE TITLE
自定义账号密码后登录失败

### ISSUE THREAD

**Issue by buliugu** [eiblog/eiblog#10]
[root@hikari home]# [GIN] 2018/04/03 - 02:16:43 | 302 |       508.9µs |   218.0.205.208 | POST     /admin/login
[GIN] 2018/04/03 - 02:16:43 | 302 |      41.565µs |   218.0.205.208 | GET      /admin/profile
[GIN] 2018/04/03 - 02:16:44 | 200 |      45.763µs |   218.0.205.208 | GET      /admin/login
从日志来看/admin/profile这边做了一个302重定向。我删掉了mongodb的数据库重试多次也是一样

**Comment by deepzz0** [comment]
@buliugu 应该是密码错误

**Comment by buliugu** [comment]
密码错误的日志是这样的
2018/04/03 03:23:09.016666 [ INFO] back.go:68: 账号或密码错误 admin, admin
[GIN] 2018/04/03 - 03:23:09 | 302 |      78.359µs |   218.0.205.208 | POST     /admin/login
[GIN] 2018/04/03 - 03:23:09 | 200 |      49.642µs |   218.0.205.208 | GET      /admin/login
不会有/admin/profile的302

数据库里是这样的
 db.account.find().pretty()
{
        "_id" : ObjectId("5ac2dedab9b090bd0e001fa9"),
        "username" : "lufashi",
        "password" : "dbd4b8e29e28e5d2a6ad64da37ef55644b55efe7d9ecd2a7809c1ea509719754",
        "token" : "",
        "email" : "211211pp@163.com",
        "phonen" : "+8618768105720",
        "address" : "",
        "createtime" : ISODate("2018-04-03T01:54:34.792Z"),
        "logintime" : ISODate("2018-04-03T01:57:22.088Z"),
        "logouttime" : ISODate("0001-01-01T00:00:00Z"),
        "loginip" : "218.0.205.208",
        "blogger" : {
                "blogname" : "路法师",
                "subtitle" : "天上白玉京，十二楼五城。",
                "beian" : "蜀 ICP 备 16021362 号",
                "btitle" : "坐忘岩",
                "copyright" : "本站使用「<a href=\"//creativecommons.org/licenses/by/4.0/\">署名 4.0 国际</a>」创作共享协议，转载请注明作者及原网址。",
                "seriessay" : "",
                "series" : [ ],
                "archivessay" : "",
                "archives" : [ ]
        }
}

**Comment by deepzz0** [comment]
@buliugu 所以你的用户名应该是 lufashi，而不是 admin

**Comment by buliugu** [comment]
admin只是拿来测试密码错误的

用lufashi和错误密码
2018/04/03 05:11:08.170874 [ INFO] back.go:68: 账号或密码错误 lufashi, 123456
[GIN] 2018/04/03 - 05:11:08 | 302 |       89.16µs |   218.0.205.208 | POST     /admin/login
[GIN] 2018/04/03 - 05:11:08 | 200 |      60.278µs |   218.0.205.208 | GET      /admin/login

用lufashi和正确密码
[root@hikari home]# [GIN] 2018/04/03 - 05:12:14 | 302 |     706.857µs |   218.0.205.208 | POST     /admin/login
[GIN] 2018/04/03 - 05:12:14 | 302 |       79.72µs |   218.0.205.208 | GET      /admin/profile
[GIN] 2018/04/03 - 05:12:15 | 200 |     101.454µs |   218.0.205.208 | GET      /admin/login

**Comment by buliugu** [comment]
releases里直接下的最新版  https://github.com/eiblog/eiblog/releases/download/v1.4.3/eiblog-v1.4.3.linux-amd64.tar.gz

**Comment by deepzz0** [comment]
@buliugu 你好，我了解了。
是这样的，你登录后会设置一个 su 的cookie，但这个 cookie 必须在 HTTPS 下才能设置成功，故你会一直进入登录状态。

解决办法：

* 你可以上 HTTPS，这样更安全也更快，我也推荐你这样做
* 你可以将 eiblog/conf/app.yml 下的 runmode 改为 dev

**Comment by buliugu** [comment]
原来如此，非常感谢
