### ISSUE TITLE
博客的后台管理是不是有一些地方有缺失啊？

### ISSUE THREAD

**Issue by wtzeng1** [eiblog/eiblog#11]
我进后台管理，发现

* 管理 -> 标签
* 设置 -> 基本
* 设置 -> 阅读

这几个的菜单的页面没有有效的内容，是本来就是这样的吗？

**Comment by deepzz0** [comment]
@wtzeng1 对的，标签页只展示你使用过的标签，另外设置里是没有东西的。

**Comment by deepzz0** [comment]
后面可以将它移除掉。

最好全站 HTTPS。其实CDN不一定必须用七牛，用七牛唯一的好处是在写 markdown 的时候可以直接在博客后台上传附件。

所以你的网站在国外的话可以考虑国外的CDN，当然你也可以使用七牛的测试 HTTPS 域名。

**Comment by wtzeng1** [comment]
好的，感谢解答😁
