### ISSUE TITLE
开始重构eiblog，你有什么想法

### ISSUE THREAD

**Issue by deepzz0** [eiblog/eiblog#25]
没想到有这么多朋友喜欢 eiblog，但确实 eiblog 比较老了，代码也不符合规范，可定制化能力差等。

本次重构保持初心，不支持主题定制，还是博客简单的样子。具体重构计划如下：

* 目录重构，目录结构 package 化
* 分离存储层（插件化），支持多类型存储后端：文件型，关系型，非关系型等。
* 依赖升级，包括ES搜索服务，依赖库版本升级
* 开发语言规范化，采用符合 go-lint 代码规范重写
* 优化前端，支持ServiceWorker等
* 配置简化，只保留必要配置，其它配置打包进服务依赖（开源Dockerfile）
* 文档更新，所有功能文档补齐，使用起来简单明了

本次重构由于工作原因完成时间会不稳定（大概会花1-2月完成），如果你有兴趣参与可以加入。

**Comment by deepzz0** [comment]
https://github.com/eiblog/eiblog/tree/v2

**Comment by razeencheng** [comment]
插件可以👍 让大家一起来写插件 😄

**Comment by deepzz0** [comment]
done

**Comment by ClarkQAQ** [comment]
用过其它博客系统，不喜欢，**不够轻**
