### ISSUE TITLE
post article failed

### ISSUE THREAD

**Issue by razeencheng** [eiblog/eiblog#31]
```
"handleAPIPostCreate.AddArticle: multiple write errors: [{write errors: [{E11000 duplicate key error collection: eiblog.article index: slug_1 dup key: { : \"linux-crontab\" }}]}, {<nil>}]"
```

**Comment by deepzz0** [comment]
Are you repetition same slug article?

**Comment by razeencheng** [comment]
maybe not.

just write in admin console.

looks like some thing wrong with auto save and post new.

**Comment by razeencheng** [comment]
l'll check it in detail later.

**Comment by deepzz0** [comment]
Yeah，it is db error, maybe the article slug “linux-crontab” already exists.

**Comment by deepzz0** [comment]
Hi, razeen, has the problem been confirmed?

**Comment by razeencheng** [comment]
It happened again， but i haven't check it。

I'll debug it tonight。

oh， i run out my poor English！

**Comment by razeencheng** [comment]
Some background page logic needs to be optimized, such as draft box articles should jump to the article list after publication, delete draft adjustment draft list, and so on. I'll take a look at it later.

**Comment by razeencheng** [comment]
just fixed.

Accidentally pushed to the [main line](https://github.com/eiblog/eiblog/commit/cfaa25e1239aba580e0718d40f1a2bf31158b217) ==.  

@deepzz0
