### ISSUE TITLE
文章莫名的会消失。。。

### ISSUE THREAD

**Issue by n1n1tom** [eiblog/eiblog#34]

**Comment by deepzz0** [comment]
请文你使用的版本是？文章发布了吗，是不是在草稿箱

**Comment by n1n1tom** [comment]
用的最新版本，前台的文章还在可能是缓存，重启后估计就没了 。打开数据库显示有数据条数，但是数据是空的
![image](https://user-images.githubusercontent.com/30972872/167559174-a1169b70-01d7-45af-86c1-c072980969bb.png)

**Comment by n1n1tom** [comment]
![image](https://user-images.githubusercontent.com/30972872/167559627-f1e90e2f-803c-4d99-89d4-7dff58c5bf13.png)
![image](https://user-images.githubusercontent.com/30972872/167559741-1b6655b9-16b6-4740-ac84-391f9282df86.png)
 文章是发布了的。草稿里面没有

**Comment by n1n1tom** [comment]
现在的话，在加入文章后台报错
![image](https://user-images.githubusercontent.com/30972872/167560156-8d71328e-0c55-4a6a-9382-81e86e6f505c.png)

**Comment by deepzz0** [comment]
我具体测试下

**Comment by deepzz0** [comment]
@n1n1tom 能提供下具体详细信息吗？
1. 数据库类型
2. 当时的操作

**Comment by n1n1tom** [comment]
@deepzz0 1.postgreSQL,2.网站正常启动运行后就没有动 ，写好配置文件，chmod a+x   后台运行主要程序，后续就没有在服务器上操作了，就正常传一些文章上去。

**Comment by deepzz0** [comment]
1. 确认是否是数据库数据损坏
2. 确认是否数据库用户拥有表权限
建议对权限这块排查下

**Comment by deepzz0** [comment]
@n1n1tom 你这边问题解决了吗
