### ISSUE TITLE
docker compose的image拼写错了。

### ISSUE THREAD

**Issue by frank-hank** [eiblog/eiblog#38]
如图：
![image](https://github.com/eiblog/eiblog/assets/91216967/c441ef0e-58e7-4120-b023-033ace3749b1)

**Comment by deepzz0** [comment]
汗，改过来了

**Comment by frank-hank** [comment]
问一下，eiblog/docs/install.md里面的这句是不是写错了呢？没有找到app/conf.yml这个文件。
![image](https://github.com/eiblog/eiblog/assets/91216967/90c77262-6f08-4024-9e73-88279ebefef1)

**Comment by deepzz0** [comment]
是文档没更新到，在根目录 conf/app.yml
