### ISSUE TITLE
mysql表结构如何生成

### ISSUE THREAD

**Issue by dahaipublic** [eiblog/eiblog#41]
表结构如何生成啊 大佬

**Comment by deepzz0** [comment]
gorm自动生成，可以参考这里：https://github.com/eiblog/eiblog/blob/v2/pkg/cache/store/rdbms.go

**Comment by dahaipublic** [comment]
好的 ,感谢

**Comment by dahaipublic** [comment]
eibolg go run pkg/cache/store/rdbms.go   这个我执行完只把包更新了一下 mysql链接配置是对的
gorm如何生成mysql数据库表 命令是啥啊 没怎么用过这个
 只能多问问了

**Comment by deepzz0** [comment]
你是刚刚开始学习go吗？建议仔细阅读代码及相关文档：https://gorm.io/zh_CN/docs/migration.html
