### ISSUE TITLE
二进制运行方式有没有详细的介绍

### ISSUE THREAD

**Issue by jinwyp** [eiblog/eiblog#42]
不喜欢docker方式运行

1. 二进制运行方式有没有详细的命令行参数介绍

2. 直接运行 ./backend log显示 运行在9001 但配置文件写的是9000

3. 如何 Running in "debug" mode. Switch to "release" mode in production.  如何运行在release 模式下？

4. app.yml 配置文件具体每项有没有详细介绍 默认里面有很多key 难道都已经配置好了？ 是官方已经注册好了 七牛 disqus 直接给我就能用了 不需要自己去注册账号？

5. 运行后 根据官方nginx 配置 结果打开域名 显示404   直接通过IP:9001 访问也是404

**Comment by deepzz0** [comment]
请确认是否下载对了二进制文件，一个是backup，一个eiblog。运行在release模式下请执行：
```
RUN_MODE=prod ./backend
```

**Comment by jinwyp** [comment]
> 请确认是否下载对了二进制文件，一个是backup，一个eiblog。运行在release模式下请执行：
> 
> ```
> RUN_MODE=prod ./backend
> ```

运行哪个? backup 还是 eiblog?

其他问题呢?

**Comment by deepzz0** [comment]
博客系统是运行 eiblog 下的 backend。app.yml和eiblog.conf里只是一个示例，里面所有的私人信息需要配置成你自己的。至于配置的获取暂时没有教程，请baidu或google。

**Comment by jinwyp** [comment]
博客是应该下载 
https://github.com/eiblog/eiblog/releases/download/v2.2.10/eiblog-v2.2.10.linux-amd64.tar.gz

这个对吧， 看来是我下载错了
