### ISSUE TITLE
归档页面日期显示 BUG

### ISSUE THREAD

**Issue by rieval** [eiblog/eiblog#5]
**使用的版本是: [v1.4.1_linux_amd64][]**

例如一篇`2017年12月25日`发表的文章，会被归档为`2017年25月` orz...

如下链接中的图所示
![img] (https://i.loli.net/2018/01/24/5a68a40eddd6f.png)

在 [v1.3.4_linux_amd64][] 版本中并没有出现这个 BUG。

此外有一点建议: 能否提供像 ququ 博客那样，每篇文章都提供 Markdown 链接并能访问 Markdown 版本呢？我觉得这是一个很好的功能。

P.S. 很喜欢你的博客系统 :)

[v1.4.1_linux_amd64]: https://github.com/eiblog/eiblog/releases/tag/v1.4.1
[v1.3.4_linux_amd64]: https://github.com/eiblog/eiblog/releases/tag/v1.3.4

**Comment by deepzz0** [comment]
感谢你的反馈，这个 bug 将在 v1.4.2 中修复。添加 markdown 链接访问暂时不回加入。

**Comment by rieval** [comment]
感谢！
期待加入的那一天。
:)
