### ISSUE TITLE
about页面不能评论

### ISSUE THREAD

**Issue by railjty** [eiblog/eiblog#6]
后台报错：{"code":2,"response":"Invalid argument, 'thread': Unable to find thread 'ident:post-about'"}
前端：Comments 获取数据失败，请稍后再试！
站点：https://jintaiyang123.org
还有就是编辑about页时参数错误：
![image](https://user-images.githubusercontent.com/30927889/36007353-0f5e8fa2-0d7d-11e8-8178-c9a1c5a37d83.png)
这些该如何解决？

**Comment by deepzz0** [comment]
1、标题，slug，内容三者不能为空，[写作须知](https://github.com/eiblog/eiblog/blob/master/docs/writing.md#%E9%83%91%E9%87%8D%E6%8F%90%E9%86%92)
2、关于页面的评论需要手动切换到 完整评论模式，我已帮你切换。新增文章添加了自动提交到 disqus 的功能，不需要手动切换。关于页面后面也会采取这样的措施

**Comment by railjty** [comment]
谢谢了！
