### ISSUE TITLE
请问自行编译的正确方法

### ISSUE THREAD

**Issue by rieval** [eiblog/eiblog#7]
我想尝试自行编译二进制文件，第一次接触 Golang ，不清楚该如何编译二进制文件。

在安装了官方的 Go 1.9.4/1.10  二进制发行版本后，我尝试使用  `go get -u github.com/eiblog/eiblog`  命令进行编译 eiblog ，没有任何提示，也确实在 bin 目录生成了名为 eiblog 的文件，但大小大约是 13Mb ，比 releases 下的文件少了 5Mb 左右。

系统是 Ubuntu 16.04 x86_64 和 Debian 8 x86_64 。

我是在 Docker 上运行博客的，eiblog 容器的系统是 Alpine Linux 3.6 。
在使用 `docker run -it` 命令运行容器时提示 `/bin/sh: /eiblog/eiblog Not Found` ，但容器里面确实有该文件。

请指教！

**Comment by deepzz0** [comment]
用这个编译命令试下：GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build

**Comment by rieval** [comment]
感谢！解决了。
请问为什么要使用这些命令呢？
我看了下 `go env` 默认下是 `GOOS=linux GOARCH=amd64` 的， `CGO_ENABLED` 的值为 `1` ，但应该没关系吧？
可以的话请解答一下，谢谢~

**Comment by deepzz0** [comment]
go 现在默认是动态编译，有些动态链接的文件 alpine 是没有的。所以需要关掉 CGO
