### ISSUE TITLE
请问可以不用CDN吗？

### ISSUE THREAD

**Issue by wtzeng1** [eiblog/eiblog#8]
没有备案，无法使用七牛CDN或者其它的国内CDN

**Comment by deepzz0** [comment]
博客只对接了七牛这一家 CDN。用不用 CDN 都可以的（不支持上传到本地），只要能填地址。

七牛好像自定义域名才需要备案，自动生成的也可以用啊

**Comment by wtzeng1** [comment]
谢谢解答，的确有一个测试用的域名
