### ISSUE TITLE
最右边有点空旷

### ISSUE THREAD

**Issue by DJxiaoyun** [eiblog/eiblog#9]
![2018-03-26 5 23 05](https://user-images.githubusercontent.com/4290613/37898207-c8ff25d2-311a-11e8-8a18-bb306b8a5a3a.png)
mac 10.13.2   chrome  版本 65.0.3325.181（正式版本） （64 位）

![2018-03-26 5 29 27](https://user-images.githubusercontent.com/4290613/37898476-7e3c3dd6-311b-11e8-8403-f943f9ae15ef.png)

Firefox 59.0.1 (64 位)

**Comment by deepzz0** [comment]
@DJxiaoyun 限制了最大宽度的，你屏幕的分辨率太高了
